### ISSUE TITLE
KIB v-bus tank level

### ISSUE THREAD

**Issue by DumpySquare** [kwindrem/TankRepeater#1]
Any thoughts, plans, or ideas for supporting KIB v-bus single wire systems?

Like this system:  https://manuals.heartlandowners.org/manuals/User%20Guides/KIB%20Multi-plex%20Control%20System%20V2.0.pdf

**Comment by kwindrem** [comment]
Not much technical information to go on. Doesn't seem to be an output from this system to other devices like Victron GX systems.

TankRepeater has been retired since the necessary functionality is now within Venus OS.

So, no plans to incorporate this or any other future work.

For what it's worth, Venus OS supports NEMA 2000 in and out for integration with multifunction displays and there is an HTML screen intended to be called up on such screens when visual integration is all that's needed. In addition, the "large" versions of Venus OS include connectivity to Node-Red and Signal-K for customizable integration.

**Comment by DumpySquare** [comment]
No, not much information out there.  I have found some details about others who have been able to decode some of the messages.  

I will close this for now, and may try submit and integration if I get much progress on it.  

Thanks
